name: Terraform Plan

on:
  pull_request:
    paths:
      - 'envs/**'
      - 'modules/**'

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  plan:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: envs/dev

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::160823835026:role/github-actions-tf-site
          aws-region: us-east-1

      - uses: hashicorp/setup-terraform@v3

      - run: terraform init

      - run: terraform fmt -check

      - run: terraform validate

      - run: terraform plan -no-color -input=false
